//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace pas.Models
{
	/// <summary>
	/// Database       : pas_db
	/// Data Source    : 127.0.0.1
	/// Server Version : 5.5.5-10.1.16-MariaDB
	/// </summary>
	public partial class pas_db : LinqToDB.Data.DataConnection
	{
		public ITable<User> Users { get { return this.GetTable<User>(); } }

		public pas_db()
		{
			InitDataContext();
		}

		public pas_db(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("users")]
	public partial class User
	{
		[PrimaryKey, NotNull    ] public string    UserId   { get; set; } // varchar(36)
		[Column,        Nullable] public string    RoleId   { get; set; } // varchar(36)
		[Column,     NotNull    ] public string    Username { get; set; } // varchar(36)
		[Column,     NotNull    ] public string    Password { get; set; } // varchar(255)
		[Column,        Nullable] public string    FullName { get; set; } // varchar(36)
		[Column,        Nullable] public string    RoleName { get; set; } // varchar(36)
		[Column,        Nullable] public DateTime? AddDate  { get; set; } // datetime
		[Column,        Nullable] public string    AddBy    { get; set; } // varchar(100)
		[Column,        Nullable] public DateTime? EditDate { get; set; } // datetime
		[Column,        Nullable] public string    EditBy   { get; set; } // varchar(100)
	}

	public static partial class TableExtensions
	{
		public static User Find(this ITable<User> table, string UserId)
		{
			return table.FirstOrDefault(t =>
				t.UserId == UserId);
		}
	}
}
